// Build art/manifest.js from whatever is actually in art/.
//
//   node tools/artManifest.mjs
//
// Also importable: `buildManifest()` is what tools/serve.mjs calls on boot, so
// adding a picture is "drop the file in, restart the server" rather than
// "remember to run a tool".
//
// The picture list used to be typed into world/maze.js by hand, with pixel
// sizes copied alongside. That breaks the moment a file is added or deleted:
// the frame is cut to a shape no image will arrive for, or a texture 404s and
// leaves a blank canvas on the wall.
//
// A browser cannot list a directory, so the list has to exist as a file. This
// writes it. Dimensions are read out of the file headers rather than guessed,
// because the frame has to be cut before the texture loads and a picture
// stretched to a frame someone estimated is exactly what this avoids.

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { join, extname } from 'node:path';

const ART_DIR = fileURLToPath(new URL('../art/', import.meta.url));
const OUT = join(ART_DIR, 'manifest.js');
const EXT = new Set(['.jpg', '.jpeg', '.png', '.webp']);

/** PNG: width and height are two big-endian 32-bit ints in the IHDR chunk. */
function pngSize(buf) {
  if (buf.length < 24) return null;
  if (buf.readUInt32BE(0) !== 0x89504e47) return null;
  return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
}

/** WebP: lossy (VP8), lossless (VP8L) and extended (VP8X) each differ. */
function webpSize(buf) {
  if (buf.length < 30) return null;
  if (buf.toString('ascii', 0, 4) !== 'RIFF') return null;
  if (buf.toString('ascii', 8, 12) !== 'WEBP') return null;
  const chunk = buf.toString('ascii', 12, 16);
  if (chunk === 'VP8X') {
    return {
      w: 1 + buf.readUIntLE(24, 3),
      h: 1 + buf.readUIntLE(27, 3),
    };
  }
  if (chunk === 'VP8 ') {
    return { w: buf.readUInt16LE(26) & 0x3fff, h: buf.readUInt16LE(28) & 0x3fff };
  }
  if (chunk === 'VP8L') {
    const b = buf.readUInt32LE(21);
    return { w: (b & 0x3fff) + 1, h: ((b >> 14) & 0x3fff) + 1 };
  }
  return null;
}

/** JPEG: walk the markers to the start-of-frame, which carries the size. */
function jpegSize(buf) {
  if (buf.length < 4 || buf[0] !== 0xff || buf[1] !== 0xd8) return null;
  let i = 2;
  while (i < buf.length - 9) {
    if (buf[i] !== 0xff) { i++; continue; }
    const marker = buf[i + 1];
    // SOF0..SOF15, excluding DHT (c4), JPG (c8) and DAC (cc).
    if (marker >= 0xc0 && marker <= 0xcf
      && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) {
      return { h: buf.readUInt16BE(i + 5), w: buf.readUInt16BE(i + 7) };
    }
    const len = buf.readUInt16BE(i + 2);
    if (len < 2) break;
    i += 2 + len;
  }
  return null;
}

/**
 * Scan art/ and rewrite art/manifest.js.
 *
 * @param {object} [opts]
 * @param {boolean} [opts.quiet] suppress the report; the count is still returned
 * @returns {Promise<number>} how many pictures went into the manifest
 */
export async function buildManifest(opts = {}) {
  // An art folder that does not exist is an ordinary state -- a fresh clone has
  // one, because the whole folder is gitignored bar two files. Treat it as
  // empty rather than as a failure.
  let names;
  try {
    names = await readdir(ART_DIR);
  } catch {
    names = [];
  }

  const files = names
    .filter((f) => EXT.has(extname(f).toLowerCase()))
    .sort((a, b) => a.localeCompare(b));

  const entries = [];
  const skipped = [];

  for (const file of files) {
    const buf = await readFile(join(ART_DIR, file));
    // Sniff the magic bytes rather than trusting the extension. art/flower1.png
    // is a JPEG with a .png name -- browsers sniff content and render it fine,
    // and a tool that believed the extension silently dropped it.
    const size = pngSize(buf) || jpegSize(buf) || webpSize(buf);
    if (!size || !size.w || !size.h) {
      skipped.push(file);
      continue;
    }
    entries.push([file, size.w, size.h]);
  }

  const body = entries
    .map(([f, w, h]) => `  [${JSON.stringify(f)}, ${w}, ${h}],`)
    .join('\n');

  const out = `// GENERATED by tools/artManifest.mjs -- do not edit by hand.
// Not in git: this is built from whatever images are in art/. See art/README.md.
//
// Every picture in art/, with its pixel dimensions read from the file header.
// Re-run after adding or removing an image:
//
//   node tools/artManifest.mjs
//
// A browser cannot list a directory, which is why this file exists at all.

export const ART = [
${body}
];

export default ART;
`;

  await writeFile(OUT, out, 'utf8');

  if (!opts.quiet) {
    console.log(`\n  scanned : ${files.length} files in art/`);
    console.log(`  written : ${entries.length} entries to art/manifest.js`);
    if (skipped.length) {
      console.log(`  skipped : ${skipped.length} unreadable -- ${skipped.join(', ')}`);
    }
    if (!entries.length) {
      console.log('\n  art/ is empty, so the maze walls will be bare.');
      console.log('  Drop .jpg / .png / .webp files in there and run this again.');
    }
  }

  return entries.length;
}

// Run directly -> do the thing. Imported -> just export it.
if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  await buildManifest();
}
